steps:
 - name: 'ubuntu'
   args: ['bash', './myscript.sh']
   env:
    - '_PR_NUMBER=$BUILD_I$_PR_NUMBER'
    - '_BASE_BRANCH=$_BASE_BRANCH'
    - '_HEAD_BRANCH=$_HEAD_BRANCH'

 - name: ubuntu
   args:
    - echo
    - $BRANCH_NAME
 - name: ubuntu
   args:
    - echo
    - $BRANCH_NAME
 - name: node
   args:
    - install
    entrypoint: npm

